name             'linuxbox'
maintainer       'Chris Olin'
maintainer_email 'contact@chrisolin.com'
license          'BSD'
description      'Provisions personal Linux environment'
long_description 'Provsions personal Linux environment'
version          '0.1.0'

depends 'ruby_rbenv'
depends 'ruby_build'
depends 'apt'
depends 'dmg'
